# Generated by Django 5.1.2 on 2025-06-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='persona',
            name='context',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='persona_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='persona',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='visibility',
            field=models.CharField(default='private', max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='persona',
            name='context_type',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='name',
        ),
    ]
