# Generated by Django 5.1.2 on 2025-06-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_persona_unique_together_persona_context_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='personas',
        ),
    ]
