# Generated by Django 5.1.2 on 2025-06-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_persona_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table=None,
        ),
    ]
