# Generated by Django 5.1.2 on 2025-08-19 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_user_last_login_device_and_more'),
        ('main', '0004_alter_persona_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_views', models.IntegerField(blank=True, default=None, null=True)),
                ('current_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='main.persona')),
            ],
            options={
                'db_table': 'persona_share_links',
                'indexes': [models.Index(fields=['share_token'], name='persona_sha_share_t_72d136_idx'), models.Index(fields=['expires_at'], name='persona_sha_expires_c61119_idx')],
            },
        ),
    ]
