# Generated by Django 5.1.2 on 2025-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('consent_type', models.CharField(max_length=100)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_version', models.CharField(default='v1', max_length=20)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'consent_type', 'consent_version')},
            },
        ),
    ]
