"""
Django settings for ContextMe project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from supabase import create_client
import dj_database_url
import os
import sentry_sdk

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fn!_c&npix)ecyu!@&rpq9x$(s9d!9n=*g1zf4b4(=i%%o82^g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = [
    'captcha',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'main',
    'consent',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ContextMe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ContextMe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Get the database URL from environment variable
DATABASE_URL = 'postgresql://postgres.hdvncgemljlwzjnhvmbg:crystal14!@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres'

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}

# Add SSL options manually
DATABASES['default']['OPTIONS'] = {
    'sslmode': 'verify-full',
    'sslrootcert': os.path.join(BASE_DIR, 'certs', 'prod-ca-2021.crt')
}

# Supabase settings
SUPABASE_URL = 'https://hdvncgemljlwzjnhvmbg.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhkdm5jZ2VtbGpsd3pqbmh2bWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzA0NjQsImV4cCI6MjA2MjU0NjQ2NH0.7jqn_Gn44rcRjrBew8dDd-SzNfsCmP3Vs4q7BuhpOR4'
SUPABASE_SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhkdm5jZ2VtbGpsd3pqbmh2bWJnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Njk3MDQ2NCwiZXhwIjoyMDYyNTQ2NDY0fQ.yTN9D-4cItODDU0k3s6Q_nb-CfzWD-DMKg1WPXgRna8'
supabase = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


RECAPTCHA_PUBLIC_KEY = '6Lc8anorAAAAAFCOqTPQdm9er-DHrsjF0TJ_uXGv'
RECAPTCHA_PRIVATE_KEY = '6Lc8anorAAAAANRYeOh2Ka-cbBablD_f7f9MObEg'

RECAPTCHA_REQUIRED_SCORE = 0.85
RECAPTCHA_USE_SSL = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True



sentry_sdk.init(
    dsn="https://955a6ba4122c473c6a8a01a7aee23aeb@o4509757855170560.ingest.de.sentry.io/4509757856809040",
    send_default_pii=True,
    traces_sample_rate=1.0,
)
