# Generated by Django 5.1.2 on 2025-05-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_gender_identity_user_pronouns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sexual_orientation',
        ),
    ]
