# Generated by Django 5.1.2 on 2025-05-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
