# Generated by Django 5.1.2 on 2025-06-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
