# Generated by Django 5.1.2 on 2025-08-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_user_last_login_device_and_more'),
    ]


