# Generated by Django 5.1.2 on 2025-08-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_user_last_login_device_and_more'),
    ]

    operations = [
        # No operations
    ]
