# Generated by Django 5.1.2 on 2025-08-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
