# Generated by Django 5.1.2 on 2025-08-29 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_admin_users_password_alter_admin_users_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_users',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin_users',
            name='admin_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin_users',
            name='admin_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='admin_users',
            table='admin_users',
        ),
    ]
